# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bBbnUqPpt0XRQhYek5TWK_Fcd0U-8BB
"""

def atm_system():
    balance = 10000

    while True:
        print("ATM MENU")
        print("1. Withdraw Money")
        print("2. Check Balance")
        print("3. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            amount = float(input("Enter withdrawal amount: "))

            if amount < 0:
                print("Invalid amount! Amount cannot be negative.")

            elif amount > balance:
                print("Insufficient balance!")

            else:
                balance = balance - amount
                print("Withdrawal successful!")
                print("Remaining balance:", balance)

        elif choice == '2':
            print("Current balance:", balance)

        elif choice == '3':
            print("Thank you for using ATM!")
            break

        else:
            print("Invalid choice! Please try again.")

atm_system()