# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jga8FL5ca42AoWuHFfwrWwDeVDZiXUQN
"""

def login_system():
    correct_username = "admin"
    correct_password = "1234"

    attempts = 0

    while attempts < 3:
        username = input("Enter username: ")
        password = input("Enter password: ")

        if username == correct_username and password == correct_password:
            print("Login Successful")
            return

        else:
            attempts += 1
            print("Invalid credentials! Attempts left:", 3 - attempts)

    print("Account Locked")



login_system()