# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T98KRY-WJgXiJ4B6U6s9wXDF3jSjEHcD
"""

def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error! Division by zero"
    return a / b


while True:
    print("Menu")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Divide")
    print("5. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 5:
        print("Exiting calculator...")
        break

    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    if choice == 1:
        print("Result:", add(num1, num2))

    elif choice == 2:
        print("Result:", subtract(num1, num2))

    elif choice == 3:
        print("Result:", multiply(num1, num2))

    elif choice == 4:
        result = divide(num1, num2)
        print("Result:", result)

    else:
        print("Invalid choice! Please select from 1 to 5.")