# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jga8FL5ca42AoWuHFfwrWwDeVDZiXUQN
"""

def generate_table(num):
    if num < 0:
        print("Negative numbers are not allowed")
    else:
        print("Multiplication Table of", num)
        for i in range(1, 11):
            print(num, "x", i, "=", num * i)


number = int(input("Enter a number"))
generate_table(number)