# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lNYQBqzzE5UsRG5KK3zNizim2aCgHZb4
"""

list = [2,4,7,8,3,5,1,10,24]

for num in list:
    if num > 0:
        print(num, "is Positive")
        if num % 2 == 0:
            print("It is Even\n")
        else:
            print("It is Odd\n")

    elif num < 0:
        print(num, "is Negative")
        if num % 2 == 0:
            print("It is Even\n")
        else:
            print("It is Odd\n")

    else:
        print(num, "is Zero (Neither Even nor Odd)\n")