# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T98KRY-WJgXiJ4B6U6s9wXDF3jSjEHcD
"""

def check_palindrome(value):
    value = str(value)
    reverse = ""
    for i in value:
        reverse = i + reverse
    if value == reverse:
        print("Palindrome")
    else:
        print("Not Palindrome")