# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T98KRY-WJgXiJ4B6U6s9wXDF3jSjEHcD
"""

rows = 5

for i in range(1, rows + 1):
    for j in range(i):

        if i % 2 == 0:
            print("*", end=" ")
        else:
            print("#", end=" ")
    print()