# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jga8FL5ca42AoWuHFfwrWwDeVDZiXUQN
"""

def calculate_bonus(salary, experience):
    if experience >= 10:
        bonus = salary * 0.20
    elif experience >= 5:
        bonus = salary * 0.10
    else:
        bonus = salary * 0.05

    total_salary = salary + bonus
    print("Salary:", salary)
    print("Experience:", experience, "years")
    print("Bonus:", bonus)
    print("Total Salary after Bonus:", total_salary)

employees = int(input("Enter number of employees: "))

for i in range(employees):
    print("Enter details for Employee", i+1)
    salary = float(input("Enter salary: "))
    experience = int(input("Enter years of experience: "))

    calculate_bonus(salary, experience)