# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGlwIlTDf74Ndbh7PPbOUDB7bJfxd-ry
"""

def calculate_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 75:
        return "B"
    elif marks >= 50:
        return "C"
    else:
        return "Fail"

for i in range(5):
    marks = int(input("Enter marks: "))
    print("Grade:", calculate_grade(marks))